name: CI

on:
  pull_request:
  push:
    branches:
      - livros

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django.ap
          POSTGRES_PASSWORD: django.ap
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        run: python -m pip install --upgrade pip poetry

      - name: Instalar Dependências
        run: poetry install --with dev --sync --no-root

      - name: Verificar se Ruff está instalado
        run: poetry run ruff --version

      - name: Corrigir problemas de linting
        run: poetry run ruff check . --fix

