name:  CI

on:
  pull_request:
  push:
    branches:
      - livros

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django.ap
          POSTGRES_PASSWORD: django.ap
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalação de Dependências (com Poetry)
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev --sync --no-root

      - name: Corrigir problemas de linting
        run: poetry run ruff check . --fix
